 enum ShopActionTypes {
  FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE',
  OPEN_ITEM_MODAL = 'OPEN_ITEM_MODAL',
  CLOSE_ITEM_MODAL = 'CLOSE_ITEM_MODAL',
};

export default ShopActionTypes;
